# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_normal <- function(centers, XIs, XmIs, yIs, ymIs, K, p, M, n) {
    .Call('_gfilinreg_f_normal', PACKAGE = 'gfilinreg', centers, XIs, XmIs, yIs, ymIs, K, p, M, n)
}

f_cauchy <- function(centers, XIs, XmIs, yIs, ymIs, K, p, M, n) {
    .Call('_gfilinreg_f_cauchy', PACKAGE = 'gfilinreg', centers, XIs, XmIs, yIs, ymIs, K, p, M, n)
}

f_student <- function(centers, XIs, XmIs, yIs, ymIs, K, p, M, n, nu) {
    .Call('_gfilinreg_f_student', PACKAGE = 'gfilinreg', centers, XIs, XmIs, yIs, ymIs, K, p, M, n, nu)
}

f_logistic <- function(centers, XIs, XmIs, yIs, ymIs, K, p, M, n) {
    .Call('_gfilinreg_f_logistic', PACKAGE = 'gfilinreg', centers, XIs, XmIs, yIs, ymIs, K, p, M, n)
}

